site.url: beeside.net
logo: logo.svg
title: BeeSide
description: Pat Petit, Full-stack developer

social:
  twitter: iamPatPetit
  github: patpetit
  instagram: patpetit.photo

google_analytics: UA-34565160-1

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

test: true